// Mocks generated by Mockito 5.4.0 from annotations
// in brain_box/test/user_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:firebase_database/firebase_database.dart' as _i2;
import 'package:firebase_database_platform_interface/firebase_database_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseReference_0 extends _i1.SmartFake
    implements _i2.DatabaseReference {
  _FakeDatabaseReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionResult_1 extends _i1.SmartFake
    implements _i2.TransactionResult {
  _FakeTransactionResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOnDisconnect_2 extends _i1.SmartFake implements _i2.OnDisconnect {
  _FakeOnDisconnect_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataSnapshot_3 extends _i1.SmartFake implements _i2.DataSnapshot {
  _FakeDataSnapshot_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseEvent_4 extends _i1.SmartFake implements _i2.DatabaseEvent {
  _FakeDatabaseEvent_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuery_5 extends _i1.SmartFake implements _i2.Query {
  _FakeQuery_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_6<T> extends _i1.SmartFake
    implements _i3.StreamSubscription<T> {
  _FakeStreamSubscription_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_7<T> extends _i1.SmartFake implements _i3.Future<T> {
  _FakeFuture_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseApp_8 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseReference].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseReference extends _i1.Mock implements _i2.DatabaseReference {
  @override
  _i2.DatabaseReference get root => (super.noSuchMethod(
        Invocation.getter(#root),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.getter(#root),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.getter(#root),
        ),
      ) as _i2.DatabaseReference);
  @override
  _i2.DatabaseReference get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.DatabaseReference);
  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.Stream<_i2.DatabaseEvent> get onChildAdded => (super.noSuchMethod(
        Invocation.getter(#onChildAdded),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> get onChildRemoved => (super.noSuchMethod(
        Invocation.getter(#onChildRemoved),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> get onChildChanged => (super.noSuchMethod(
        Invocation.getter(#onChildChanged),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> get onChildMoved => (super.noSuchMethod(
        Invocation.getter(#onChildMoved),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> get onValue => (super.noSuchMethod(
        Invocation.getter(#onValue),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i2.DatabaseReference child(String? path) => (super.noSuchMethod(
        Invocation.method(
          #child,
          [path],
        ),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #child,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #child,
            [path],
          ),
        ),
      ) as _i2.DatabaseReference);
  @override
  _i2.DatabaseReference push() => (super.noSuchMethod(
        Invocation.method(
          #push,
          [],
        ),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #push,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #push,
            [],
          ),
        ),
      ) as _i2.DatabaseReference);
  @override
  _i3.Future<void> set(Object? value) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setWithPriority(
    Object? value,
    Object? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWithPriority,
          [
            value,
            priority,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> update(Map<String, Object?>? value) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setPriority(Object? priority) => (super.noSuchMethod(
        Invocation.method(
          #setPriority,
          [priority],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> remove() => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<_i2.TransactionResult> runTransaction(
    _i5.TransactionHandler? transactionHandler, {
    bool? applyLocally = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runTransaction,
          [transactionHandler],
          {#applyLocally: applyLocally},
        ),
        returnValue:
            _i3.Future<_i2.TransactionResult>.value(_FakeTransactionResult_1(
          this,
          Invocation.method(
            #runTransaction,
            [transactionHandler],
            {#applyLocally: applyLocally},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.TransactionResult>.value(_FakeTransactionResult_1(
          this,
          Invocation.method(
            #runTransaction,
            [transactionHandler],
            {#applyLocally: applyLocally},
          ),
        )),
      ) as _i3.Future<_i2.TransactionResult>);
  @override
  _i2.OnDisconnect onDisconnect() => (super.noSuchMethod(
        Invocation.method(
          #onDisconnect,
          [],
        ),
        returnValue: _FakeOnDisconnect_2(
          this,
          Invocation.method(
            #onDisconnect,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeOnDisconnect_2(
          this,
          Invocation.method(
            #onDisconnect,
            [],
          ),
        ),
      ) as _i2.OnDisconnect);
  @override
  _i3.Future<_i2.DataSnapshot> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i3.Future<_i2.DataSnapshot>.value(_FakeDataSnapshot_3(
          this,
          Invocation.method(
            #get,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DataSnapshot>.value(_FakeDataSnapshot_3(
          this,
          Invocation.method(
            #get,
            [],
          ),
        )),
      ) as _i3.Future<_i2.DataSnapshot>);
  @override
  _i3.Future<_i2.DatabaseEvent> once(
          [_i5.DatabaseEventType? eventType = _i5.DatabaseEventType.value]) =>
      (super.noSuchMethod(
        Invocation.method(
          #once,
          [eventType],
        ),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #once,
            [eventType],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #once,
            [eventType],
          ),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i2.Query startAt(
    Object? value, {
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAt,
          [value],
          {#key: key},
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #startAt,
            [value],
            {#key: key},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #startAt,
            [value],
            {#key: key},
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query startAfter(
    Object? value, {
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAfter,
          [value],
          {#key: key},
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #startAfter,
            [value],
            {#key: key},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #startAfter,
            [value],
            {#key: key},
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query endAt(
    Object? value, {
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #endAt,
          [value],
          {#key: key},
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #endAt,
            [value],
            {#key: key},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #endAt,
            [value],
            {#key: key},
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query endBefore(
    Object? value, {
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #endBefore,
          [value],
          {#key: key},
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #endBefore,
            [value],
            {#key: key},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #endBefore,
            [value],
            {#key: key},
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query equalTo(
    Object? value, {
    String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #equalTo,
          [value],
          {#key: key},
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #equalTo,
            [value],
            {#key: key},
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #equalTo,
            [value],
            {#key: key},
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query limitToFirst(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limitToFirst,
          [limit],
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #limitToFirst,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #limitToFirst,
            [limit],
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query limitToLast(int? limit) => (super.noSuchMethod(
        Invocation.method(
          #limitToLast,
          [limit],
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #limitToLast,
            [limit],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #limitToLast,
            [limit],
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query orderByChild(String? path) => (super.noSuchMethod(
        Invocation.method(
          #orderByChild,
          [path],
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByChild,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByChild,
            [path],
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query orderByKey() => (super.noSuchMethod(
        Invocation.method(
          #orderByKey,
          [],
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByKey,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByKey,
            [],
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query orderByValue() => (super.noSuchMethod(
        Invocation.method(
          #orderByValue,
          [],
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByValue,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByValue,
            [],
          ),
        ),
      ) as _i2.Query);
  @override
  _i2.Query orderByPriority() => (super.noSuchMethod(
        Invocation.method(
          #orderByPriority,
          [],
        ),
        returnValue: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByPriority,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeQuery_5(
          this,
          Invocation.method(
            #orderByPriority,
            [],
          ),
        ),
      ) as _i2.Query);
  @override
  _i3.Future<void> keepSynced(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #keepSynced,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Stream].
///
/// See the documentation for Mockito's code generation for more information.
class MockStream extends _i1.Mock implements _i3.Stream<_i2.DatabaseEvent> {
  @override
  bool get isBroadcast => (super.noSuchMethod(
        Invocation.getter(#isBroadcast),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i3.Future<int> get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
  @override
  _i3.Future<bool> get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<_i2.DatabaseEvent> get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.getter(#first),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.getter(#first),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Future<_i2.DatabaseEvent> get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.getter(#last),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.getter(#last),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Future<_i2.DatabaseEvent> get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.getter(#single),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.getter(#single),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> asBroadcastStream({
    void Function(_i3.StreamSubscription<_i2.DatabaseEvent>)? onListen,
    void Function(_i3.StreamSubscription<_i2.DatabaseEvent>)? onCancel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #asBroadcastStream,
          [],
          {
            #onListen: onListen,
            #onCancel: onCancel,
          },
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.StreamSubscription<_i2.DatabaseEvent> listen(
    void Function(_i2.DatabaseEvent)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_6<_i2.DatabaseEvent>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
        returnValueForMissingStub: _FakeStreamSubscription_6<_i2.DatabaseEvent>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i3.StreamSubscription<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> where(bool Function(_i2.DatabaseEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<S> map<S>(S Function(_i2.DatabaseEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [convert],
        ),
        returnValue: _i3.Stream<S>.empty(),
        returnValueForMissingStub: _i3.Stream<S>.empty(),
      ) as _i3.Stream<S>);
  @override
  _i3.Stream<E> asyncMap<E>(
          _i3.FutureOr<E> Function(_i2.DatabaseEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncMap,
          [convert],
        ),
        returnValue: _i3.Stream<E>.empty(),
        returnValueForMissingStub: _i3.Stream<E>.empty(),
      ) as _i3.Stream<E>);
  @override
  _i3.Stream<E> asyncExpand<E>(
          _i3.Stream<E>? Function(_i2.DatabaseEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncExpand,
          [convert],
        ),
        returnValue: _i3.Stream<E>.empty(),
        returnValueForMissingStub: _i3.Stream<E>.empty(),
      ) as _i3.Stream<E>);
  @override
  _i3.Stream<_i2.DatabaseEvent> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleError,
          [onError],
          {#test: test},
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<S> expand<S>(Iterable<S> Function(_i2.DatabaseEvent)? convert) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [convert],
        ),
        returnValue: _i3.Stream<S>.empty(),
        returnValueForMissingStub: _i3.Stream<S>.empty(),
      ) as _i3.Stream<S>);
  @override
  _i3.Future<dynamic> pipe(
          _i3.StreamConsumer<_i2.DatabaseEvent>? streamConsumer) =>
      (super.noSuchMethod(
        Invocation.method(
          #pipe,
          [streamConsumer],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Stream<S> transform<S>(
          _i3.StreamTransformer<_i2.DatabaseEvent, S>? streamTransformer) =>
      (super.noSuchMethod(
        Invocation.method(
          #transform,
          [streamTransformer],
        ),
        returnValue: _i3.Stream<S>.empty(),
        returnValueForMissingStub: _i3.Stream<S>.empty(),
      ) as _i3.Stream<S>);
  @override
  _i3.Future<_i2.DatabaseEvent> reduce(
          _i2.DatabaseEvent Function(
            _i2.DatabaseEvent,
            _i2.DatabaseEvent,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Future<S> fold<S>(
    S? initialValue,
    S Function(
      S,
      _i2.DatabaseEvent,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _FakeFuture_7<S>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeFuture_7<S>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
      ) as _i3.Future<S>);
  @override
  _i3.Future<String> join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i3.Future<String>.value(''),
        returnValueForMissingStub: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
  @override
  _i3.Future<bool> contains(Object? needle) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [needle],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<dynamic> forEach(void Function(_i2.DatabaseEvent)? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValue: _i3.Future<dynamic>.value(),
        returnValueForMissingStub: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
  @override
  _i3.Future<bool> every(bool Function(_i2.DatabaseEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> any(bool Function(_i2.DatabaseEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Stream<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: _i3.Stream<R>.empty(),
        returnValueForMissingStub: _i3.Stream<R>.empty(),
      ) as _i3.Stream<R>);
  @override
  _i3.Future<List<_i2.DatabaseEvent>> toList() => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
        ),
        returnValue:
            _i3.Future<List<_i2.DatabaseEvent>>.value(<_i2.DatabaseEvent>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i2.DatabaseEvent>>.value(<_i2.DatabaseEvent>[]),
      ) as _i3.Future<List<_i2.DatabaseEvent>>);
  @override
  _i3.Future<Set<_i2.DatabaseEvent>> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue:
            _i3.Future<Set<_i2.DatabaseEvent>>.value(<_i2.DatabaseEvent>{}),
        returnValueForMissingStub:
            _i3.Future<Set<_i2.DatabaseEvent>>.value(<_i2.DatabaseEvent>{}),
      ) as _i3.Future<Set<_i2.DatabaseEvent>>);
  @override
  _i3.Future<E> drain<E>([E? futureValue]) => (super.noSuchMethod(
        Invocation.method(
          #drain,
          [futureValue],
        ),
        returnValue: _FakeFuture_7<E>(
          this,
          Invocation.method(
            #drain,
            [futureValue],
          ),
        ),
        returnValueForMissingStub: _FakeFuture_7<E>(
          this,
          Invocation.method(
            #drain,
            [futureValue],
          ),
        ),
      ) as _i3.Future<E>);
  @override
  _i3.Stream<_i2.DatabaseEvent> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> takeWhile(
          bool Function(_i2.DatabaseEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> skipWhile(
          bool Function(_i2.DatabaseEvent)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> distinct(
          [bool Function(
            _i2.DatabaseEvent,
            _i2.DatabaseEvent,
          )? equals]) =>
      (super.noSuchMethod(
        Invocation.method(
          #distinct,
          [equals],
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
  @override
  _i3.Future<_i2.DatabaseEvent> firstWhere(
    bool Function(_i2.DatabaseEvent)? test, {
    _i2.DatabaseEvent Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Future<_i2.DatabaseEvent> lastWhere(
    bool Function(_i2.DatabaseEvent)? test, {
    _i2.DatabaseEvent Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Future<_i2.DatabaseEvent> singleWhere(
    bool Function(_i2.DatabaseEvent)? test, {
    _i2.DatabaseEvent Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Future<_i2.DatabaseEvent> elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.DatabaseEvent>.value(_FakeDatabaseEvent_4(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        )),
      ) as _i3.Future<_i2.DatabaseEvent>);
  @override
  _i3.Stream<_i2.DatabaseEvent> timeout(
    Duration? timeLimit, {
    void Function(_i3.EventSink<_i2.DatabaseEvent>)? onTimeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #timeout,
          [timeLimit],
          {#onTimeout: onTimeout},
        ),
        returnValue: _i3.Stream<_i2.DatabaseEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.DatabaseEvent>.empty(),
      ) as _i3.Stream<_i2.DatabaseEvent>);
}

/// A class which mocks [FirebaseDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseDatabase extends _i1.Mock implements _i2.FirebaseDatabase {
  @override
  _i4.FirebaseApp get app => (super.noSuchMethod(
        Invocation.getter(#app),
        returnValue: _FakeFirebaseApp_8(
          this,
          Invocation.getter(#app),
        ),
        returnValueForMissingStub: _FakeFirebaseApp_8(
          this,
          Invocation.getter(#app),
        ),
      ) as _i4.FirebaseApp);
  @override
  set app(_i4.FirebaseApp? _app) => super.noSuchMethod(
        Invocation.setter(
          #app,
          _app,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set databaseURL(String? _databaseURL) => super.noSuchMethod(
        Invocation.setter(
          #databaseURL,
          _databaseURL,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<dynamic, dynamic> get pluginConstants => (super.noSuchMethod(
        Invocation.getter(#pluginConstants),
        returnValue: <dynamic, dynamic>{},
        returnValueForMissingStub: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  void useDatabaseEmulator(
    String? host,
    int? port,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #useDatabaseEmulator,
          [
            host,
            port,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.DatabaseReference reference() => (super.noSuchMethod(
        Invocation.method(
          #reference,
          [],
        ),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #reference,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #reference,
            [],
          ),
        ),
      ) as _i2.DatabaseReference);
  @override
  _i2.DatabaseReference ref([String? path]) => (super.noSuchMethod(
        Invocation.method(
          #ref,
          [path],
        ),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #ref,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #ref,
            [path],
          ),
        ),
      ) as _i2.DatabaseReference);
  @override
  _i2.DatabaseReference refFromURL(String? url) => (super.noSuchMethod(
        Invocation.method(
          #refFromURL,
          [url],
        ),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #refFromURL,
            [url],
          ),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.method(
            #refFromURL,
            [url],
          ),
        ),
      ) as _i2.DatabaseReference);
  @override
  void setPersistenceEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setPersistenceEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setPersistenceCacheSizeBytes(int? cacheSize) => super.noSuchMethod(
        Invocation.method(
          #setPersistenceCacheSizeBytes,
          [cacheSize],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setLoggingEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setLoggingEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<void> goOnline() => (super.noSuchMethod(
        Invocation.method(
          #goOnline,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> goOffline() => (super.noSuchMethod(
        Invocation.method(
          #goOffline,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> purgeOutstandingWrites() => (super.noSuchMethod(
        Invocation.method(
          #purgeOutstandingWrites,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DataSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSnapshot extends _i1.Mock implements _i2.DataSnapshot {
  @override
  _i2.DatabaseReference get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeDatabaseReference_0(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub: _FakeDatabaseReference_0(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i2.DatabaseReference);
  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  Iterable<_i2.DataSnapshot> get children => (super.noSuchMethod(
        Invocation.getter(#children),
        returnValue: <_i2.DataSnapshot>[],
        returnValueForMissingStub: <_i2.DataSnapshot>[],
      ) as Iterable<_i2.DataSnapshot>);
  @override
  bool hasChild(String? path) => (super.noSuchMethod(
        Invocation.method(
          #hasChild,
          [path],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  _i2.DataSnapshot child(String? path) => (super.noSuchMethod(
        Invocation.method(
          #child,
          [path],
        ),
        returnValue: _FakeDataSnapshot_3(
          this,
          Invocation.method(
            #child,
            [path],
          ),
        ),
        returnValueForMissingStub: _FakeDataSnapshot_3(
          this,
          Invocation.method(
            #child,
            [path],
          ),
        ),
      ) as _i2.DataSnapshot);
}
